### ISSUE TITLE
Localization: Strings

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1092]
seconds remaining calculated in Utilites.FormatRemainingTime
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6cf988ff-a0e2-4913-bda9-1e046fa9c11c)

**Comment by beccamc** [comment]
I think this was fixed, except for strings coming from service hub.

**Comment by LittleLittleCloud** [comment]
![image](https://user-images.githubusercontent.com/16876986/109219289-443db480-776c-11eb-90d4-626d9228a39f.png)

**Comment by LittleLittleCloud** [comment]
The training time finished without any mode trained window is not fixed
![image](https://user-images.githubusercontent.com/16876986/109219606-a8607880-776c-11eb-99d3-7c11fdd11a10.png)

**Comment by beccamc** [comment]
@zewditu  were you investigating what we need to do to get localization on the service hub side?

**Comment by zewditu** [comment]
I did not start the investigation yet, but it is already in the backlog.

**Comment by beccamc** [comment]
Sorry, I didn't realize this was fixed. @vzhuqin here are the instructions for validating. 

1.  Installing a different language on your VS. 
Vs Installer -> _VS version_ -> Modify -> Language packs
2. Make training fail by running out of time. Use 1-2 seconds and any dataset should fail.

**Comment by vzhuqin** [comment]
@beccamc I verified this issue according to the instructions on:

- main build: 16.6.3.2136604
- two languages: CHS and ESP

Find that below strings are not localized, please take a look.

String 1: Error
String 2: Yes
String 3: No
String 4: Model Builder Error
String 5: Close
Strings 6: Failed.
Strings 7: Try training your model for more time.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ecfe7b0f-adfa-490b-b37d-3f31e865cfb8)

**Comment by zewditu** [comment]
For  ![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/b2f9a2c6-b782-498b-bf27-b1eaa5ba47fc)

it seems that  these strings  ( error , yes and no) are not the in  string resource file in Model builder  they are coming from VS message box . 
@beccamc  is this the VS bug ? because I am excepting that if the string is from VS that is  not our responsibility  or do we need to customize message box ? any thought on this ?

**Comment by zewditu** [comment]
For
 ![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/89879f03-71ef-4286-86fc-8e3260a0c3a3)

It seems translated. The screenshots below show English and French versions.
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/4ed320c0-eb42-48da-88c2-511cdbc663d7)

**Comment by zewditu** [comment]
For the case of localization issue here
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/cc898524-f7b8-4b81-b59a-36c20b2b5fba)

The window is VS Message Box. The language for the Message box is coming from the  OS.

**Comment by beccamc** [comment]
@zewditu Can this issue be closed if the Error, Yes and No are from the OS?
