### ISSUE TITLE
Error when machine learning is to be added to my project.

### ISSUE THREAD

**Issue by alozino** [dotnet/machinelearning-modelbuilder#1661]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.6.1.2131904
 - Visual Studio Version (if applicable): 16.5.0

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
- Clear description of the problem:

**To Reproduce**
1. Go to Solution Explorer 
2. Right Click on the project name
3. Scroll down to "Add" and Click Machine Learning

**Expected behavior**
The Select Machine Learning page ought to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/43538635/127712578-8fc8de72-2e17-4318-a86b-30a6dd9f4d31.png)

**Comment by beccamc** [comment]
@alozino Sorry you ran into this problem and thanks for reporting. Can you copy the log file mentioned in the error message? Thanks!

**Comment by alozino** [comment]
> @alozino Sorry you ran into this problem and thanks for reporting. Can you copy the log file mentioned in the error message? Thanks!
Hi Becca, Thanks for your reply. Here's the file below. 
You will need to change its extension to XML. since XML files are not allowed on this sit.

Thanks.

[ActivityLog - Copy.xml.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6918674/ActivityLog.-.Copy.xml.txt)

**Comment by beccamc** [comment]
Sorry for the delay here @alozino. We just released a new version. for VS 2019. Can you try to update and see if the problem continues? https://marketplace.visualstudio.com/items?itemName=MLNET.07. Thanks!

**Comment by alozino** [comment]
@beccamc Thanks for your support. The issue still persists even after the update. Please I need help with this issue.

**Comment by beccamc** [comment]
Do you have VS 2022 also installed? Looks like the same error as #1630?

**Comment by beccamc** [comment]
Any update here? Did updating work?

**Comment by beccamc** [comment]
Sorry, I don't have enough information to help here. If anyone else has problems with loading Model Builder check out our troubleshooting guide - https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#i-cannot-add-machine-learning-to-my-project

In this case it looks like Model Builder had some installation problem. I would try uninstalling, and then updating to your latest version. Ping me if you're still having problems!

**Comment by alozino** [comment]
> Sorry for the delay here @alozino. We just released a new version. for VS 2019. Can you try to update and see if the problem continues? https://marketplace.visualstudio.com/items?itemName=MLNET.07. Thanks!

Sorry for replying late, yes the update worked. And it is working perfectly now.
