### ISSUE TITLE
Cannot see the close icon X and search icon in dark theme.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1673]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 2.1
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Model builder Error dialog and Advanced data options dialog in dark theme.
- Clear description of the problem:

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 Preview start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Set to Dark color theme from Tools>Options>General;
4. Add model builder by right click on the project;
5. Select Recommendation scenario to start training;
6. Pop up Model Builder Error dialog, the close icon X  is not visible;
![image](https://user-images.githubusercontent.com/81727020/128111973-aef0dcd8-c736-4570-b41f-82f8abc15372.png)
7. Close the error dialog, open Advanced data options dialog, the search icon is not visible.
![image](https://user-images.githubusercontent.com/81727020/128111981-19d77263-ff5a-4155-8f8b-81bd8a2de6a0.png)

**Expected behavior**
All icons can be visible in dark theme.

**Comment by vzhuqin** [comment]
Cannot see the background of buttons which is disabled status, and the box of code snippet on Consume page is not obvious, could you help to take a look at this?
- ML.NET Model Builder from Main:
16.7.4.2143102
- VS2022:
Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 4.0 [31630.363.main]

![image](https://user-images.githubusercontent.com/81727020/131651795-2e776322-e537-40bd-9128-10fdaa021a40.png)
![image](https://user-images.githubusercontent.com/81727020/131651949-460be2ce-e2a0-47fc-8c82-52d062526c55.png)

![image](https://user-images.githubusercontent.com/81727020/131652757-f83d1de1-66a1-4f2b-a516-22f972bcfeca.png)

**Comment by beccamc** [comment]
@vzhuqin Can you check this again? It may have been fixed by Xiaoyun icon fixes

**Comment by vzhuqin** [comment]
Verify this issue on latest main build: 16.7.4.2145201
The background of Consume page is still not obvious, could you help to take a look again?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3491292a-e0a9-4d55-93ca-444915cc599b)
Others are fixed as below screenshots.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/122cb6d6-dd5d-4b69-96c1-7428370436e6)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/6ab42118-7721-4885-8597-c952b7e35784)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/28ba9544-e4ab-45d4-a31f-e46167fa8a2a)
