### ISSUE TITLE
Can't add data without VS crashing

### ISSUE THREAD

**Issue by PtrStruct** [dotnet/machinelearning-modelbuilder#1696]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_
2019 Version 16.11.0

**Bug description**
When I go to add my VoTT Json file that was exported using VoTT, Visual Studio crashes.
What I did was, I opened up VoTT, added some images, marked them and tagged them.
Then I exported it and went to go upload the json file in the model builder where you're suppose to do so when using the Object Detection one. During "Data".

**Steps to Reproduce**
Install
https://marketplace.visualstudio.com/items?itemName=MLNET.07

Follow this guide and download the test dataset
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder
Download: https://aka.ms/mlnet-object-detection-tutorial-assets

Create a .NET Core Console project 5.0 or 3.1, it occurs in both.

Go to Project -> Add -> Machine Learning
Select Object Detection
Fill out your Azure details

And add the test data that was provided in the next step under "Data", as soon as I do that VS freezes and then restarts.
I've tried it with my own dataset too.

**Expected Experience**
It should let me go to the next step.

**Actual Experience**
Visual Studio Crashes and restarts

**Additional Context**
Can I get a hold of a log to share that would probably visualize this issue better?

**Comment by zewditu** [comment]
@ptrStruct  I am not able to reproduce the issues  in the latest Model Builder, could you update your Model Builder 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5a31adf9-c1e5-42f3-bfb3-881b55c0596d)

**Comment by PtrStruct** [comment]
I'm pretty sure I'm using the most recent version.
![bild](https://user-images.githubusercontent.com/39096940/129669975-0db36cc1-dc3a-4986-9cb7-1f9909634787.png)

**Comment by zewditu** [comment]
Thanks for the confirmation,  I have an internal build that is  ahead of you,  this issue will not shown in the next release

**Comment by PtrStruct** [comment]
When will this be available?

**Comment by zewditu** [comment]
We are targetting to release in sepetember

**Comment by vzhuqin** [comment]
Not repro this issue.
- ML.Net Model Builder: 16.7.2.2142301 (main build)
- Microsoft Visual Studio Enterprise 2019: 16.11.1
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e7616986-50c7-4c3f-ad35-3176a4550195)

**Comment by beccamc** [comment]
@PtrStruct this issue should be resolved. Please download the latest build from https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by PtrStruct** [comment]
Running this version and I'm still experiencing the same issue unfortunately.
![bild](https://user-images.githubusercontent.com/39096940/134067654-d187cc4b-0728-4a04-b286-a5dcaddc1652.png)

**Comment by beccamc** [comment]
@PtrStruct Looks like your VS is in English. Is your machine in a different language that uses "," decimal separator? 

@LittleLittleCloud Is this the same as the "," issue for non-US culture?

**Comment by PtrStruct** [comment]
@beccamc Holy smokes that was a fast response!
My machine should be installed using a English language pack, but there could be something hiding since my keyboard layout is Swedish.

**Comment by beccamc** [comment]
I think this is the same problem as #1701. You need to get the default to ".".  I think changing to "en-US" would do it. 

We have a fix for this, but it won't ship for a few more weeks.

**Comment by LittleLittleCloud** [comment]
Looks like the same issue to me

**Comment by PtrStruct** [comment]
@beccamc @LittleLittleCloud I managed to solve the issue by heading into the "Region" tab in windows, then moving over to "Additional Settings.." and changing the decimal symbol to `.`.

Thanks! 😄

**Comment by beccamc** [comment]
Great! Glad you were able to fix it! You should be able to change that setting back when we release a new version. Thanks!
