### ISSUE TITLE
Value prediction: After changing the feature column 's Data type from "Single" to "String", the training should be completed successfully for Data source from SQLPassword.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2074]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.5.2216801 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.11); 2022(17.1.1)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: Training Value prediction with Data source from SQLPassword.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**

  1. Pre-requisite: Do [Pre-requisites/SQLPassword](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md) before repro this issue.
  2. Select Create a new project from the Visual Studio start window;
  4. Choose the C# Console App (.NET Core) project template;
  5. Add model builder by right click on the project;
  6. Select Value prediction scenario>Local (CPU);
  7. On Data page, select>SQL Server>Microsoft SQL Server>SQL Server Authentication to input the data source;
  8. Choose "fare_amount" as label and then click "Avanced data option".
  9. Change **"rate_code" or "passenger_count" or "trip_time_in_secs" or "trip_distance"** column 's Data type from "Single" to "String" and save it.
  10. Click Start training button, prompt model builder error as below screenshot.

**Expected behavior**
The training should be completed successfully after changing the feature column 's Data type from "Single" to "String".

**Screenshots**
Data settings:
![image](https://user-images.githubusercontent.com/99375895/159425678-9df70994-008c-4cca-ba9c-415f8222e912.png)

Error screenshot:
![image](https://user-images.githubusercontent.com/99375895/159425833-7ea7a707-1aa4-4232-a36f-3c038b9b41b5.png)

**Additional context**
When do the same thing for the .csv file data source, the training can be completed successfully.
![image](https://user-images.githubusercontent.com/99375895/159426565-59710623-35b3-4f95-88b2-a78c0dcf2d19.png)
![image](https://user-images.githubusercontent.com/99375895/159426703-be551344-7a0e-43bf-9a92-fb41da9c7f15.png)

**Comment by v-Hailishi** [comment]
Verified on the latest main build: 16.14.0.2255803, the error message has been changed like below:
1. Change "rate_code" or "passenger_count" column 's Data type from "Single" to "String".
<img width="478" alt="image" src="https://user-images.githubusercontent.com/99375895/201038906-37677e83-9d8b-48db-bffe-5cf10490b8d2.png">

2. Change "trip_time_in_secs" or "trip_distance" column 's Data type from "Single" to "String".
<img width="482" alt="image" src="https://user-images.githubusercontent.com/99375895/201038780-097a18bd-16dc-4942-877b-9fbd268ee02a.png">

**Comment by beccamc** [comment]
I think this is fixed by https://github.com/dotnet/machinelearning-tools/pull/1676. @v-Hailishi Can you validate this?

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build: 17.14.3.2311302
1. Change "rate_code" or "passenger_count" column 's Data type from "Single" to "String".
![image](https://user-images.githubusercontent.com/99375895/218653677-8b7eb16d-eb49-4704-b507-eba48bb720b6.png)

2. Change "trip_time_in_secs" or "trip_distance" column 's Data type from "Single" to "String".
![image](https://user-images.githubusercontent.com/99375895/218653424-aefb849d-80a7-4c4a-9d27-3b822683fb69.png)

**Comment by LittleLittleCloud** [comment]
We do the type cast in SQL command string and there're cases that one type can't be casted to another type. Overall, I feel like the case is we should disable the datatype change function for SQL data source.

thoughts? @JakeRadMSFT  @luisquintanilla

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2320602.
![image](https://user-images.githubusercontent.com/99375895/230844757-2d0e41a2-fc38-43f6-a352-d43afddb8d96.png)
