### ISSUE TITLE
dotnet/sdk/6.0.203/NuGet.targets(466,5): error MSB4044: 

### ISSUE THREAD

**Issue by cuicaihao** [dotnet/machinelearning-modelbuilder#2122]
Running  [ML.Net Tutorial](https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume) with .Net6.0.203.

To step: Consume your model.

macOS Monterey version 12.4.

~/Documents/Developer/dotnet/ml.net/myMLApp/SentimentModel ·················································  base  system  19:02:20

```bash
  ~/Documents/Developer/dotnet/ml.net/myMLApp/SentimentModel ·················································  base  system  19:09:56
❯ ll
total 640
-rw-r--r--  1 caihaocui  staff   1.1K 20 May 18:54 Program.cs
-rw-r--r--  1 caihaocui  staff   2.3K 20 May 18:54 SentimentModel.consumption.cs
-rw-r--r--  1 caihaocui  staff   8.2K 20 May 18:54 SentimentModel.mbconfig
-rw-r--r--  1 caihaocui  staff   2.0K 20 May 18:54 SentimentModel.training.cs
-rw-r--r--  1 caihaocui  staff   292K 20 May 18:54 SentimentModel.zip
drwxr-xr-x  3 caihaocui  staff    96B 20 May 19:01 bin
  ~/Documents/Developer/dotnet/ml.net/myMLApp/SentimentModel ·················································  base  system  19:09:58
❯ dotnet run
/usr/local/share/dotnet/sdk/6.0.203/NuGet.targets(466,5): error MSB4044: The "GetRestoreProjectStyleTask" task was not given a value for the required parameter "MSBuildProjectName". [/Users/caihaocui/Documents/Developer/dotnet/ml.net/myMLApp/SentimentModel/.csproj]

The build failed. Fix the build errors and run again.
  ~/Documents/Developer/dotnet/ml.net/myMLApp/SentimentModel ·················································  base  system  19:10:01
❯ 
```

**Comment by LittleLittleCloud** [comment]
Looks like it's missing .csproj in generated project, I can take a look

**Comment by LittleLittleCloud** [comment]
@cuicaihao  should be fixed now.

**Comment by cuicaihao** [comment]
Hi @LittleLittleCloud, I just re-do the tutorial on my mac, it is still the same issue.
```bash
  ~/Doc/Dev/V/ML.Net/myMLApp/SentimentModel ···  base  system  21:23:18
❯ ls -a
.                             SentimentModel.mbconfig
..                            SentimentModel.training.cs
.csproj                       SentimentModel.zip
Program.cs                    bin
SentimentModel.consumption.cs obj
  ~/Documents/Developer/VS.Net/ML.Net/myMLApp/SentimentModel ······························  base  system  21:23:23
❯ dotnet run 
/usr/local/share/dotnet/sdk/6.0.300/NuGet.targets(466,5): error MSB4044: The "GetRestoreProjectStyleTask" task was not given a value for the required parameter "MSBuildProjectName". [/Users/caihaocui/Documents/Developer/VS.Net/ML.Net/myMLApp/SentimentModel/.csproj]

The build failed. Fix the build errors and run again.
  ~/Documents/Developer/VS.Net/ML.Net/myMLApp/SentimentModel ······························  base  system  21:23:35
❯ dotnet --list-sdks
3.1.419 [/usr/local/share/dotnet/sdk]
6.0.300 [/usr/local/share/dotnet/sdk]
  ~/Documents/Developer/VS.Net/ML.Net/myMLApp/SentimentModel ·  base  system  21:31:07
❯ 
```

Here is the project snapshot:

![dotnet ML issue iShot_2022-06-25_21 26 27](https://user-images.githubusercontent.com/3784477/175771508-b2f6c467-a4cc-4803-9c72-f8c2c80cd157.jpg)

Reference: https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/intro 

My OS:  
- macOS 12.4 (Monterey) CPU Intel Core i5. 
- dotnet 6.0.300
