### ISSUE TITLE
Authentication failed when using Chinese Azure with modelbuilder

### ISSUE THREAD

**Issue by haoxin** [dotnet/machinelearning-modelbuilder#2134]
suspect 'setup workspace' refers to azure global endpoints but not Chinese endpoints.

**Comment by beccamc** [comment]
@haoxin Sorry you ran into this problem. Are you have the same problem as this issue - https://github.com/dotnet/machinelearning-modelbuilder/issues/2118?

**Comment by haoxin** [comment]
> @haoxin Sorry you ran into this problem. Are you have the same problem as this issue - #2118?

Yes.

**Comment by beccamc** [comment]
@haoxin What region are you in? According to [docs]( https://docs.microsoft.com/en-us/azure/machine-learning/reference-machine-learning-cloud-parity#azure-china-21vianet) looks like CH-East-2 is supported and CH-North-3 is not supported. Are you using CH-East-2?

**Comment by haoxin** [comment]
Yes, we used CH-east-2

**Comment by haoxin** [comment]
> @haoxin What Azure region are you using? According to [docs](https://docs.microsoft.com/en-us/azure/machine-learning/reference-machine-learning-cloud-parity#azure-china-21vianet) looks like CH-East-2 is supported and CH-North-3 is not supported. Are you using CH-East-2?

Yes, We used CH-east-2

**Comment by beccamc** [comment]
@v-Hailishi Can you try to repro this with a CH-east-2 region?

**Comment by v-Hailishi** [comment]
@beccamc The "ML.NET Model Builder Demo" subscription cannot support the CH-east-2 region.
Could you help to provide a special subscription which can support the CH-east-2 region?
<img width="622" alt="image" src="https://user-images.githubusercontent.com/99375895/173289303-538036b1-c480-4d22-bbd6-b711a8dc02d7.png">

**Comment by haoxin** [comment]
> 

Hello Haili,
    May I contact with you offline and provide you an Azure China ML workspace to do a test? thanks.

**Comment by v-Hailishi** [comment]
@beccamc  I have reproduced this issue after using the account provided by haoxin.
The following are the repro steps:
1. Add the China Azure cloud: https://login.chinacloudapi.cn
![image](https://user-images.githubusercontent.com/99375895/176582290-8235e5b1-3bd4-489b-b5ba-e910047b5076.png)
2. On the "Set up workspace" dialog, select "Azure in China".
![image](https://user-images.githubusercontent.com/99375895/176582732-22e48087-0e5f-41e9-9640-24e8b832aa49.png)
3. After you enter the account, you will see the 401 error.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/99375895/176582999-a4f2941a-40ff-4236-a5d3-613153663f26.png">

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please test / validate that this has been fixed in the latest build. Thanks

**Comment by v-Hailishi** [comment]
@luisquintanilla The bug is still repro on the latest main branch: 16.13.9.2241103
![image](https://user-images.githubusercontent.com/99375895/184271717-3ab75d47-92bb-4e23-9471-aad902b6f076.png)

**Comment by beccamc** [comment]
@haoxin We just released a new version that upgrades some calls to use the Azure SDK. Can you re-try on your side and see if you still see the same error message?

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate using the latest version. Thanks.

**Comment by v-Hailishi** [comment]
@luisquintanilla On the latest main branch 16.13.10.2246201 still can see 401 error:
![image](https://user-images.githubusercontent.com/99375895/189824091-6ea71652-a2f6-4328-bea0-47a3940df8de.png)

**Comment by luisquintanilla** [comment]
Hmm. Thanks for checking. 

cc @beccamc

**Comment by luisquintanilla** [comment]
@zewditu to confirm whether 401 comes back from SDK call. If so, file an issue with SDK.

**Comment by zewditu** [comment]
The workspace creation part  is note done by the new Azure SDK we are still stick with the old SDK

**Comment by beccamc** [comment]
What is the plan to update to the new Azure SDK for this?

**Comment by zewditu** [comment]
The reason we still use the old SDK is the new SDK does not let us create dependent resources of a workspace like a key vault, application insight and storage account, and container registry automatically.

**Comment by zewditu** [comment]
@v-Hailishi  can you validate this on this  private build
https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/Fixenv/atom.xml

**Comment by v-Hailishi** [comment]
@beccamc This bug is also repro on the private build
https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/Fixenv/atom.xml
![image](https://user-images.githubusercontent.com/99375895/191689106-49fc1b59-a7ac-45d9-8d3a-68e577648dc4.png)

**Comment by zewditu** [comment]
@v-Hailishi  thanks for checking

**Comment by zewditu** [comment]
@v-Hailishi, I made some changes, could you try this build ?https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/Fixenv/atom.xml

**Comment by v-Hailishi** [comment]
@zewditu This bug has been fixed on the private build 16.13.10.2247202
https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/Fixenv/atom.xml
![image](https://user-images.githubusercontent.com/99375895/191884734-8598ebc4-edc1-40f5-bc63-217c51d43ac9.png)

**Comment by zewditu** [comment]
@v-Hailishi thanks for testing !

**Comment by beccamc** [comment]
This will ship with the Fall release.

**Comment by beccamc** [comment]
This fix has shipped with release [16.14.0](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)
