### ISSUE TITLE
Forecasting: The generated Console App and Web Api projects run failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2249]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2246601 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App and Web Api projects are run failed.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv
https://github.com/dotnet/machinelearning-samples/raw/main/samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/Data/DailyDemand.mdf

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Forecasting"** scenario and data source to complete the training;
  5. Click "Add to solution" button on the Consume page to generate Console App and Web Api projects.
  6. Run the generated Console App and Web Api projects.
  
**Expected behavior**
The generated Console App and Web Api projects should run successfully.

**Screenshot**
File (.csv, .tsv, .txt) and SQL Server>Microsoft SQL Server:
![image](https://user-images.githubusercontent.com/99375895/190980929-71a7131e-e02e-4a9d-8028-413104112a52.png)
![image](https://user-images.githubusercontent.com/99375895/190980990-301c041e-41f7-4078-8439-d2980fe5bcf0.png)

SQL Server>Microsoft SQL Server Database File:
![image](https://user-images.githubusercontent.com/99375895/190981307-76aad735-f333-4d37-a3eb-4de40c730aba.png)
![image](https://user-images.githubusercontent.com/99375895/190981328-30f0b058-4d0e-4bbe-bd9e-f18443d442c5.png)

**Comment by LittleLittleCloud** [comment]
should already be fixed in main

**Comment by v-Hailishi** [comment]
@LittleLittleCloud The bug is still repro on the latest main branch: 16.13.10.2246901

**Comment by luisquintanilla** [comment]
@LittleLittleCloud I see you merged a PR for this one. Are we okay to close?

**Comment by LittleLittleCloud** [comment]
I think so but before closing that let me re-validate it again

**Comment by LittleLittleCloud** [comment]
not fixed

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2255301
![image](https://user-images.githubusercontent.com/99375895/199929370-5d016198-16ed-4111-8367-a75910cb3dd1.png)
