### ISSUE TITLE
mlnet forecasting CLI doesn't appear to work

### ISSUE THREAD

**Issue by jsobell** [dotnet/machinelearning-modelbuilder#2287]
Running the cli using the command `mlnet forecasting` returns the error `No valid columns to save`

**To Reproduce**
Create a CSV datafile with anything in it.
Run `mlnet forecasting --dataset "myDataSet.csv" --label-col total --has-header true --time-col datetime --horizon 2 --train-time 100`

```
Start Training
start nni training
Experiment output folder: C:\Users\user\AppData\Local\Temp\AutoML-NNI\Experiment-XLUOMA
Forcasting
System.InvalidOperationException: No valid columns to save
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.InitializeForecasting(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 141
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 51
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 65
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, CancellationToken cancellationToken, CancellationToken timeout) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 163
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(TrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
:
:
```

Contents of log file shows:
```
2022-10-13 17:33:16.3528 DEBUG System.FormatException: String ' available trainer: LGBM, RF, FASTTREE, LBFGS, SDCA ' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at Microsoft.ML.CLI.FeatureFlagManager.ReadFeatureFlags(String ffPath) in /_/src/mlnet/FeatureFlagManager.cs:line 64 (Microsoft.ML.CLI.FeatureFlagManager.ReadFeatureFlags)
2022-10-13 17:33:16.4112 DEBUG Set log file path to C:\Users\user\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-10-13 17:33:16.4112 DEBUG Set log level to Info (Microsoft.ML.CLI.Commands.MLCommand.set_Verbosity)
2022-10-13 17:33:16.7683 INFO Start Training (Microsoft.ML.CLI.Runners.AutoMLRunner+<ExecuteAsync>d__8.MoveNext)
2022-10-13 17:33:16.8298 INFO start nni training (Microsoft.ML.CLI.Utilities.PBarConsolePrinter.Print)
2022-10-13 17:33:16.8446 INFO Experiment output folder: C:\Users\user\AppData\Local\Temp\AutoML-NNI\Experiment-XLUOMA (Microsoft.ML.CLI.Utilities.PBarConsolePrinter.Print)
2022-10-13 17:33:16.8446 DEBUG row count is unknown, count it explicitly (Microsoft.ML.CLI.Runners.AutoMLRunner.Instance_DiagnosticDataReceived)
2022-10-13 17:33:16.8627 DEBUG count elapse 16ms (Microsoft.ML.CLI.Runners.AutoMLRunner.Instance_DiagnosticDataReceived)
2022-10-13 17:33:16.8627 INFO Forcasting (Microsoft.ML.CLI.Utilities.PBarConsolePrinter.Print)
2022-10-13 17:33:16.9278 ERROR System.InvalidOperationException: No valid columns to save
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.InitializeForecasting(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 141
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 51
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 65
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, CancellationToken cancellationToken, CancellationToken timeout) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 163
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(TrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 88
   at Microsoft.ML.CLI.Program.TrainAsync(TrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 348
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 329
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_6>d.MoveNext() in /_/src/mlnet/Program.cs:line 235
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
```

**Comment by LittleLittleCloud** [comment]
The error message indicates that it fails to find 'total' and `datetime` column from your dataset. Would you mind share a snapshot of your dataset, thanks

**Comment by jsobell** [comment]
Here's the dataset:
[dataset.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/9781029/dataset.csv)
We experimented with different formats for the datetime column, as there's no obvious documented example showing the expected format.
Changing `--label-col` and `--time-col` to non-existent columns does show an error, so it's clearly recognising those columns from the datasource.

**Comment by jsobell** [comment]
Any progress on this? Is it a mistake in my dataset, or is there a bug?

**Comment by natehitze** [comment]
I'm having the exact same issue: same exception, stack trace, logs etc. In the experiment output folder there's just an empty `train.bin`. Tool version 16.13.9

I tried using TSV instead of CSV, with/without header, using column names/using column indices. I wasn't able to get it to work with any of those combinations.

**Comment by ramzzzay** [comment]
I'm here with the same problem:

> mlnet forecasting --dataset "day_clear.csv" --horizon 7 --label-col 2 --time-col 0 --has-header true --name test1 --train-time 60

> MacBook Pro 2021 16'' 16/512 m1 pro

> mlnet --version
16.13.9+3066041f1761935763bdd267a9bcbb64cb3ec543

[day_clear.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/9944674/day_clear.csv)

**Comment by Wintermute79** [comment]
Same here. What date / time formats are valid?

**Comment by LittleLittleCloud** [comment]
Sorry for the late reply @jsobell. The cause of this issue is `DataFrame` can't handle datetime format.
We are working on this issue by including the fix for parsing datetime format in mlnet (#https://github.com/dotnet/machinelearning/pull/6302) but that change hasn't been included in mlnet.cli yet. Once we update mlnet.cli and target to latest mlnet, this issue will go.

**Comment by LittleLittleCloud** [comment]
The fix has merged in, should work now.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest CLI version 16.14.3.
![image](https://user-images.githubusercontent.com/99375895/215729947-ea945b23-c64a-4757-ab1f-dc035df15391.png)

**Comment by Wintermute79** [comment]
I latest Visual Studio 2002 version 17.4.4
with updated NuGet packages
Microsoft.Extensions.ML to 2.0.0 (latest)
Microsoft.ML.TimeSeries to 2.0.0 (latest)
and it still crashes as soon as I start the training via UI:

![devenv_ivx2Bldh2D](https://user-images.githubusercontent.com/11521470/215821061-17e19f01-cb03-4f56-9d55-16db0c5ea7bb.png)


![devenv_lpeIXn0BFP](https://user-images.githubusercontent.com/11521470/215821288-5409ac43-1df4-485b-850b-0f5d4241da29.png)
